In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.2.1+cu121


In [3]:
# Check for GPU access with PyTorch
print(torch.cuda.is_available())

True


In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of GPU
device_count = torch.cuda.device_count()
device_count

1

In [6]:
# Putting tensors and models on the GPU
tensor = torch.tensor([12,3,4,5], device = device)
tensor

tensor([12,  3,  4,  5], device='cuda:0')

In [7]:
# Moving back to CPU
# tensor = tensor.to("cpu")

tensor = tensor.cpu()
tensor.numpy()

array([12,  3,  4,  5])

In [8]:
!nvidia-smi

Wed Mar 13 22:58:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0              29W /  70W |    105MiB / 15360MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.tensor()`. Detail available at https://pytorch.org/docs/stable/tensors.html

In [9]:
# scalar

scalar = torch.tensor(7)
scalar
print(type(scalar))

<class 'torch.Tensor'>


In [10]:
array = torch.tensor([[1,2], [2,3]])

In [11]:
print(type(array))

<class 'torch.Tensor'>


In [12]:
print(array.ndim)

2


In [13]:
# MATRIX

MATRIX = torch.Tensor([[7,8],
                       [9, 10]])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9., 10.])

In [17]:
type(MATRIX)

torch.Tensor

In [18]:
type(MATRIX)

torch.Tensor

In [19]:
# tensor

tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor.ndim

3

In [22]:
tensor[0][1]

tensor([4, 5, 6])

#### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [23]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(3,4)

In [24]:
random_tensor

tensor([[0.1344, 0.6673, 0.4193, 0.7022],
        [0.5225, 0.6360, 0.9211, 0.9501],
        [0.9229, 0.3372, 0.5173, 0.1890]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor.shape

torch.Size([3, 4])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
random_image_size_tensor

tensor([[[0.5049, 0.2346, 0.7066],
         [0.6147, 0.3465, 0.4908],
         [0.6534, 0.3295, 0.2740],
         ...,
         [0.1244, 0.0289, 0.5503],
         [0.5090, 0.7736, 0.7965],
         [0.4706, 0.9726, 0.1538]],

        [[0.4784, 0.9836, 0.9341],
         [0.1574, 0.3336, 0.2262],
         [0.2371, 0.0242, 0.1040],
         ...,
         [0.4659, 0.6486, 0.9797],
         [0.6879, 0.2893, 0.7531],
         [0.6275, 0.6619, 0.7968]],

        [[0.9584, 0.8125, 0.5252],
         [0.1121, 0.0608, 0.8906],
         [0.6626, 0.0621, 0.1378],
         ...,
         [0.6191, 0.9472, 0.7380],
         [0.7582, 0.1141, 0.2596],
         [0.8721, 0.0693, 0.9871]],

        ...,

        [[0.3395, 0.6299, 0.2288],
         [0.5149, 0.0317, 0.8846],
         [0.6739, 0.5691, 0.8068],
         ...,
         [0.2316, 0.5382, 0.1646],
         [0.8057, 0.7599, 0.9673],
         [0.5023, 0.4064, 0.9361]],

        [[0.1447, 0.3106, 0.3173],
         [0.5375, 0.8416, 0.8063],
         [0.

## Zeros and ones

In [29]:
# create the tensors of all zeros
zeros = torch.zeros(size=(3,4))

In [30]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# create a tensor of all ones
ones = torch.ones(size=(4,3))

In [33]:
ones
ones.dtype

torch.float32

In [34]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [35]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [36]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 10, step = 3)

In [37]:
one_to_ten

tensor([0, 3, 6, 9])

In [38]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [39]:
ten_zeros

tensor([0, 0, 0, 0])

## Tensor datatypes

In [40]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #
                               device=None,
                               requires_grad=False)

In [41]:
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
print(float_32_tensor.device)

cpu


In [44]:
test = torch.rand(10, 3, 4)

In [45]:
test

tensor([[[0.2441, 0.4672, 0.0388, 0.1658],
         [0.7966, 0.4371, 0.3196, 0.2685],
         [0.9140, 0.2568, 0.7711, 0.0781]],

        [[0.3857, 0.0684, 0.1392, 0.9317],
         [0.0335, 0.4161, 0.4932, 0.6748],
         [0.1941, 0.9730, 0.6842, 0.1563]],

        [[0.8421, 0.2811, 0.7972, 0.7534],
         [0.6929, 0.6840, 0.3508, 0.2250],
         [0.1647, 0.0538, 0.5512, 0.5136]],

        [[0.1921, 0.8170, 0.2415, 0.5351],
         [0.1158, 0.6661, 0.7811, 0.2932],
         [0.1330, 0.1471, 0.1758, 0.7733]],

        [[0.6207, 0.7787, 0.4447, 0.2239],
         [0.1260, 0.4106, 0.3338, 0.9766],
         [0.5252, 0.6481, 0.5809, 0.6462]],

        [[0.4697, 0.8106, 0.3060, 0.1382],
         [0.9028, 0.1719, 0.8036, 0.6464],
         [0.6145, 0.8566, 0.0254, 0.0478]],

        [[0.1030, 0.8273, 0.0367, 0.3682],
         [0.2403, 0.6508, 0.0579, 0.7614],
         [0.8553, 0.5120, 0.1804, 0.8110]],

        [[0.6553, 0.8178, 0.6560, 0.6644],
         [0.7635, 0.1398, 0.3070, 0.9948

In [46]:
test = torch.arange(1, 10).reshape(1, 3, 3)
print(test)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [47]:
test[:, 2, 1]

tensor([8])